# Default values for canfail.

replicaCount: 1

busybox:
  image: busybox
  tag: latest
  pullPolicy: IfNotPresent

requests:
  cpu: 100m
  memory: 128Mi

command:
  init: "echo $HOSTNAME is an init container and will be done soon && sleep 10 && exit 0"
  appLoop: "echo $HOSTNAME will run for an hour && while true; do sleep 3600; done"
