# Default values for canfail.

replicaCount: 1

busybox:
  image: busybox
  tag: latest
  pullPolicy: IfNotPresent

requests:
  cpu: 100m
  memory: 128Mi

failJob: false
failInit: false

command:
  appLoop: "echo $HOSTNAME will run for an hour && while true; do sleep 3600; done"
  initSuccess: "echo $HOSTNAME is an init container that will SUCCEED soon && sleep 10 && exit 0"
  initFail: "echo $HOSTNAME is an init container that will FAIL soon && sleep 10 && exit 1"
  jobSuccess: "echo $HOSTNAME is a job that will SUCCEED soon && sleep 20 && exit 0"
  jobFail: "echo $HOSTNAME is a job that will FAIL soon && sleep 20 && exit 1"
