apiVersion: apps/v1
kind: Deployment
metadata:
  name: canfail-app
  labels:
    app: canfail
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: canfail
  template:
    metadata:
      labels:
        app: canfail
    spec:
      initContainers:
      - name: canfail-app
        image: "{{ .Values.busybox.image}}:{{ .Values.busybox.tag }}"
        imagePullPolicy: {{ .Values.busybox.pullPolicy | quote }}
        resources:
          requests:
            cpu: {{ .Values.requests.cpu }}
            memory: {{ .Values.requests.memory }}
        {{ if .Values.failInit}}
        command:
          # Go with init FAIL
          - "sh"
          - "-c"
          - {{ .Values.command.initFail | quote }}
        {{ else }}
        # Go with init SUCCESS
        command:
        - "sh"
        - "-c"
        - {{ .Values.command.initSuccess | quote }}
        {{ end }}
      containers:
      - name: canfail-app-init
        image: "{{ .Values.busybox.image}}:{{ .Values.busybox.tag }}"
        imagePullPolicy: {{ .Values.busybox.pullPolicy | quote }}
        resources:
          requests:
            cpu: {{ .Values.requests.cpu }}
            memory: {{ .Values.requests.memory }}
        command:
        - "sh"
        - "-c"
        - {{ .Values.command.appLoop | quote }}
