# Default values for gb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1 

resources:
  requests:
    cpu: 50m
    memory: 50Mi

nodeSelector: {}

tolerations: []

affinity: {}
